<?php
/**
 * Created by PhpStorm.
 * User: Steven O'Driscoll
 * Date: 8/1/2018
 * Time: 8:30 PM
 */

namespace Core\Router;
include 'GetRoutes.php';

class MatchRoutes extends GetRoutes
{
    public function __construct()
    {
        parent::__construct();
        $this->url = $_SERVER['QUERY_STRING'];
    }

    public function setup($debug = '')
    {
        $this->setupRoutes($debug);
        $router = $this->matchRoutes($this->url);

        if ($debug)
        {

            if ($router)
            {
                $this->displayRoutes($this->getParams(), true);
            }
            else
            {
                $this->displayRoutes("No route found for URL $this->url", true);
            }
        }
    }

    protected function matchRoutes($url)
    {
        // $reg_exp = "/^(?P<controller>[a-z]+)\/(?P<action>[a-z]+)$/";
        if ($url === '' || $url === 'home' || $url === 'Home')
        {
            $url = 'Home/index';
        }

        foreach ($this->routes as $route => $params)
        {
            if (preg_match($route, $url, $matches))
            {
                // $params = [];

                foreach ($matches as $key => $match)
                {
                    if (is_string($key))
                    {
                        $params[$key] = $match;
                    }
                }

                $this->params = $params;
                return true;
            }
        }

        return false;
    }

    protected function getParams()
    {
        return $this->params;
    }

    protected function displayRoutes($routes, $dump)
    {
        parent::displayRoutes($routes, $dump); // TODO: Change the autogenerated stub

    }

}